feat(pre-commit): uses a temporary test environment to prevent false-positive results from testing directly from the workspace

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -4,23 +4,29 @@ function error() {
     tput setaf 1
     echo "$1"
     tput sgr0
+    exit 1
 }
 
-if ! dotnet test > /dev/null 2>&1; then
-    error "Tests failed"
-    exit 1
-fi
+REPO_ROOT=$(pwd)
+
+echo "Testing added code..."
+tempdir=$(mktemp -d)
+trap 'rm -rf "$tempdir"' EXIT
+
+git archive --format=tar HEAD | tar -xC "$tempdir"
+git checkout-index -af --prefix="${tempdir}/"
+
+cd "$tempdir" || error "Failed to setup test environment. Try again later"
+if ! dotnet test > /dev/null 2>&1; then error "Tests failed"; fi
 echo "Tests passed"
 
+
+cd "$REPO_ROOT"
 echo "Formatting code..."
 mapfile -t files < <(git diff --cached --name-only -- '*.cs')
 
 if (( ${#files[@]} > 0 )); then
-    if ! dotnet format --include "${files[@]}" > /dev/null 2>&1; then
-        error "Formatting failed"
-        exit 1
-    fi
-    
+    dotnet format --include "${files[@]}" > /dev/null 2>&1 || error "Formatting failed"
     git add "${files[@]}"
 fi
 
